# Generated by Django 4.1.11 on 2023-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0002_item_property_layer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_property',
            name='END_DATETIME',
        ),
        migrations.RemoveField(
            model_name='item_property',
            name='LAST_UPDT_DATE',
        ),
        migrations.RemoveField(
            model_name='item_property',
            name='PROPERTY_DATE',
        ),
        migrations.RemoveField(
            model_name='item_property',
            name='START_DATETIME',
        ),
        migrations.AddField(
            model_name='item_property',
            name='END_DATETIME_tempt',
            field=models.BigIntegerField(default=9999999999999),
        ),
        migrations.AddField(
            model_name='item_property',
            name='LAST_UPDT_DATE_tempt',
            field=models.BigIntegerField(default=1698182986000),
        ),
        migrations.AddField(
            model_name='item_property',
            name='PROPERTY_DATE_tempt',
            field=models.BigIntegerField(default=1698182986000),
        ),
        migrations.AddField(
            model_name='item_property',
            name='START_DATETIME_tempt',
            field=models.BigIntegerField(default=1698182986000),
        ),
    ]
