# Generated by Django 4.1.11 on 2023-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_property', '0003_remove_item_property_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_property',
            old_name='END_DATETIME_tempt',
            new_name='END_DATETIME',
        ),
        migrations.RenameField(
            model_name='item_property',
            old_name='LAST_UPDT_DATE_tempt',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.RenameField(
            model_name='item_property',
            old_name='PROPERTY_DATE_tempt',
            new_name='PROPERTY_DATE',
        ),
        migrations.RenameField(
            model_name='item_property',
            old_name='START_DATETIME_tempt',
            new_name='START_DATETIME',
        ),
    ]
