# Generated by Django 4.1.11 on 2023-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_link',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='type_link',
            name='LAST_UPDT_DATE_t',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
