# Generated by Django 4.1.11 on 2023-11-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_link', '0002_remove_type_link_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_link',
            old_name='LAST_UPDT_DATE_t',
            new_name='LAST_UPDT_DATE',
        ),
    ]
