# Generated by Django 4.1.11 on 2023-10-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('log_type', models.CharField(max_length=255)),
                ('error_message', models.TextField(null=True)),
                ('layer', models.CharField(max_length=255, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(max_length=250, null=True)),
                ('is_read', models.BooleanField()),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
            ],
        ),
    ]
