# Generated by Django 4.1.11 on 2023-11-07 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resources_drawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CULTURE', models.CharField(db_index=True, max_length=10)),
                ('ID', models.CharField(max_length=100)),
                ('SHORT_LABEL', models.CharField(max_length=200, null=True)),
                ('MOBILE_LABEL', models.CharField(max_length=200, null=True)),
                ('LAYER_LEVEL', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('ICON', models.CharField(max_length=100, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('IS_ITEM', models.CharField(max_length=50, null=True)),
                ('HIDDEN', models.CharField(max_length=10, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default='4d3a7fb0eec24807a1c3849475a95cec', max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, default='e240f00e3e614aeaacae3c2f192dcf21', max_length=32)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('SORT_ORDER', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
                ('CHILD', models.ManyToManyField(blank=True, related_name='child', to='resources_drawer.resources_drawer')),
            ],
        ),
    ]
