# Generated by Django 4.1.11 on 2023-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources_drawer',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='resources_drawer',
            name='LAST_UPDT_DATES',
            field=models.BigIntegerField(default=1699356132000),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='2044c08d946a47089e78a1492eee340d', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='83ff3a6a31b747afab262b6c87677cbd', max_length=32),
        ),
    ]
