# Generated by Django 4.1.11 on 2023-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0002_remove_resources_drawer_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources_drawer',
            old_name='LAST_UPDT_DATES',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ea348a3669a942a4b2c96be86f6267ff', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='d56207aa6b95456d8d1336e1b54e9cc7', max_length=32),
        ),
    ]
