# Generated by Django 4.1.13 on 2023-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0003_rename_last_updt_dates_resources_drawer_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_drawer',
            name='PATH',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='355630deb4cb44308b206dfc9b15045e', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='4b042b65ec084471a81d2a1f47e209eb', max_length=32),
        ),
    ]
