# Generated by Django 4.1.13 on 2023-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workflows',
            fields=[
                ('NAME', models.CharField(db_index=True, max_length=50)),
                ('CODE', models.CharField(db_index=True, max_length=100)),
                ('TYPE', models.CharField(max_length=14)),
                ('ITEM_ID', models.JSONField(default=list)),
                ('TAG_ID', models.JSONField(default=list)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default='2023-12-02', null=True)),
                ('VERSION', models.CharField(max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
