# Generated by Django 4.1.8 on 2023-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='ITEM_ID',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='TAG_ID',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='VERSION',
            field=models.CharField(default='8dc417711dcb476390ded637c63d5067', max_length=32),
        ),
    ]
