# Generated by Django 4.1.8 on 2023-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflows_item_id_alter_workflows_tag_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-11', null=True),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='VERSION',
            field=models.CharField(default='f1b65d7c62074c048938ad5f6e15bcb9', max_length=32),
        ),
    ]
