# Generated by Django 4.1.8 on 2023-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflows_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='VERSION',
            field=models.CharField(default='2096a9d50d5b47ad8ff60248b7205435', max_length=32),
        ),
    ]
