# Generated by Django 4.1.8 on 2023-05-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflows_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='VERSION',
            field=models.CharField(default='6a025e47ddf54b7abf614eae252b6340', max_length=32),
        ),
    ]
