# Generated by Django 4.1.8 on 2023-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflows_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-29', null=True),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='ROW_ID',
            field=models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='VERSION',
            field=models.CharField(max_length=32),
        ),
    ]
