# Generated by Django 4.1.8 on 2023-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_workflows_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-31', null=True),
        ),
    ]
