# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_alter_workflows_last_updt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-11-07', null=True),
        ),
    ]
