# Generated by Django 4.1.11 on 2023-10-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_list',
            name='LAST_UPDT_DATE_tempt',
            field=models.BigIntegerField(null=True),
        ),
    ]
