# Generated by Django 4.1.11 on 2023-10-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0002_code_list_last_updt_date_tempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
        ),
    ]
