# Generated by Django 4.1.11 on 2023-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0003_remove_code_list_last_updt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_list',
            name='LAST_UPDT_DATE_tempt',
        ),
        migrations.AddField(
            model_name='code_list',
            name='LAST_UPDT_DATE',
            field=models.BigIntegerField(default=1697757191000, null=True),
        ),
    ]
