# Generated by Django 4.1.8 on 2023-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0003_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ad279e0ce3ed403285f24d091aa9893b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='ac77a744f58e4d66bad18dfe47b96484', max_length=32, null=True),
        ),
    ]
