# Generated by Django 4.1.8 on 2023-05-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0004_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='fba4dacb45ff4cf7af5127112b93e77a', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='fb0b2767d2594d48832263453e53125a', max_length=32, null=True),
        ),
    ]
