# Generated by Django 4.1.8 on 2023-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0005_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d81fbeb0953640abab3d390390874f7a', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='fdca4be196274318b724060dce32ab6b', max_length=32, null=True),
        ),
    ]
