# Generated by Django 4.1.8 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0007_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ac6d21cb36d84469accccc2a18f838f1', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='66da7258d559484180d32f99b5f4826b', max_length=32, null=True),
        ),
    ]
