# Generated by Django 4.1.8 on 2023-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0008_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a82c7af751bd419c95387865d2c59b80', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='188182560d8347cebd713eb9c8eb9468', max_length=32, null=True),
        ),
    ]
