# Generated by Django 4.1.8 on 2023-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0009_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='017dad70be424b25a48fab4a4782a326', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='02883501ef0c4d2b8e550c79acd8a4c1', max_length=32, null=True),
        ),
    ]
