# Generated by Django 4.1.8 on 2023-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0010_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='fc1e06d057d244e39e43c768e1c0e276', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='b583abee9aae42c49a0e0e4bd56e69e6', max_length=32, null=True),
        ),
    ]
