# Generated by Django 4.1.8 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0012_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4b30ead7d39642c996a9f2776443a52b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='7fc7fd2752f94f4ca40573b3b3df9dee', max_length=32, null=True),
        ),
    ]
