# Generated by Django 4.1.8 on 2023-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0013_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='046cd80604b241b4a22b861f5cb73f38', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='ccf6c5afb80a411bba671b7588e692cc', max_length=32, null=True),
        ),
    ]
