# Generated by Django 4.1.8 on 2023-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0014_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='457c0ed38a8e4ca1af5a995190675419', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='1231bcf89afb4e45bedb01ee856343e0', max_length=32, null=True),
        ),
    ]
