# Generated by Django 4.1.8 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0015_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b1fd479f41374592b3f47fd2afd76b6e', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='02e6f7a423234a6f8ee467adef019804', max_length=32, null=True),
        ),
    ]
