# Generated by Django 4.1.8 on 2023-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0016_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7d48dfa5c65547c3a04f4d2e220def24', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='adfbd964e07049efa36e718d31dba111', max_length=32, null=True),
        ),
    ]
