# Generated by Django 4.1.8 on 2023-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0017_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='da83c3bb34c748b78f159614b5a36df2', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='6ea22e38899c4d48a711375aa3baf272', max_length=32, null=True),
        ),
    ]
