# Generated by Django 4.1.8 on 2023-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0018_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6f377da135124331a865dbb6793e8e7b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='da3cc6d9a9ff4a2580f996971170c489', max_length=32, null=True),
        ),
    ]
