# Generated by Django 4.1.8 on 2023-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0019_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='bab3390bb5154fbdbb5a4158a9475a1e', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='fbf35d36b8214e73b7c2933f9a5a9e26', max_length=32, null=True),
        ),
    ]
