# Generated by Django 4.1.8 on 2023-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0020_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='dd6faa48f2fd433593e1c7d3105a0dc3', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='bd9c529d69344946baea011612474a4e', max_length=32, null=True),
        ),
    ]
