# Generated by Django 4.1.8 on 2023-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0022_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b19f045939e04f3b9ebad609d888664f', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='8f38df4d3b694ff7aafdac87fe862c4c', max_length=32, null=True),
        ),
    ]
