# Generated by Django 4.1.8 on 2023-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0023_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c04e53ca0f9d4f548ea93c1f8009d660', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='bc4861b788c247d0a7c1292719a55b56', max_length=32, null=True),
        ),
    ]
