# Generated by Django 4.1.8 on 2023-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0024_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ce6c33a788084289ad734b0f07b7d3c2', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='80ac05d8cded43debb3d00d4cb0aa2f0', max_length=32, null=True),
        ),
    ]
