# Generated by Django 4.1.8 on 2023-06-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0025_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='8c2cb08fb0404f608b3df1b001987553', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='55b314a1f88548908167d13f9179941f', max_length=32, null=True),
        ),
    ]
