# Generated by Django 4.1.8 on 2023-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0026_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='8c4425accc974a8ea4243c119af92cb8', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='de06a1079fe7417390d13175fe8bb64b', max_length=32, null=True),
        ),
    ]
