# Generated by Django 4.1.8 on 2023-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0027_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='MOBILE_LABEL',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b58964b5c4fc4d628f214a201cc7ccbc', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='SHORT_LABEL',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='2d4f82502d074d8a9a5042bf86406233', max_length=32, null=True),
        ),
    ]
