# Generated by Django 4.1.11 on 2023-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0028_alter_resources_types_mobile_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_types',
            name='DESCRIPTION',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='07475b25dfdd4cfdbe93ce4a6af6598b', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='663312be2c0a45b5986020da1acfb831', max_length=32, null=True),
        ),
    ]
