# Generated by Django 4.1.11 on 2023-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0029_resources_types_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_types',
            name='LAST_UPDT_DATE_tempt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6eced17187b34555b49f7a43fd755fff', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='4905296285b64d398bc45e9bd989a0b6', max_length=32, null=True),
        ),
    ]
