# Generated by Django 4.1.11 on 2023-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0030_resources_types_last_updt_date_tempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='724c646ceefd47dd8fca836fbf25582f', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='93dfe6a6a565440880770e7e3898928c', max_length=32, null=True),
        ),
    ]
