# Generated by Django 4.1.11 on 2023-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0031_alter_resources_types_row_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources_types',
            name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='LAST_UPDT_DATE_tempt',
            field=models.BigIntegerField(default=1698924959000, null=True),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='41b5905bc3ac4ff6abb1be84dfe66d59', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='bc4a05829cea43228a58b3e30a34cd50', max_length=32, null=True),
        ),
    ]
