# Generated by Django 4.1.11 on 2023-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0032_remove_resources_types_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources_types',
            old_name='LAST_UPDT_DATE_tempt',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='39a29d5d56c047e19498634d7bb1c3ca', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='16006ca094d64e2b80cfc75d79b43051', max_length=32, null=True),
        ),
    ]
