# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_types', '0033_rename_last_updt_date_tempt_resources_types_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_types',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='ad0adc62c3d841fa9ed3d7f7ae114598', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_types',
            name='VERSION',
            field=models.CharField(default='57c01f30119c4ad490a4a536121c8d7f', max_length=32, null=True),
        ),
    ]
