x-default-logging: &default-logging
  driver: json-file
  options:
    max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
    max-file: "${DOCKER_LOG_MAX_FILE:-5}"

services:
  couchserver:
    image: couchdb:latest
    restart: always
    container_name: ligeiaai-couchserver-1
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-change-me}
    volumes:
      - couch-data:/opt/couchdb/data
      - ./couchdb/local.d/99-cors.ini:/opt/couchdb/etc/local.d/99-cors.ini:ro
    networks:
      - app_net
    logging: *default-logging
  elasticsearch:
    profiles:
      - search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=my-cluster"
      - "node.name=node-1"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_net
    logging: *default-logging
  postgres:
    restart: unless-stopped
    image: postgres:11.20-alpine
    container_name: ligeiaai-postgres-1
    volumes:
      - postgres-data1:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASS:-postgres}
      - POSTGRES_DB=${PG_DB:-demo}
    ports:
      - "${PG_EXPOSE_PORT:-5434}:5432"
    networks:
      - app_net
    logging: *default-logging
  pgadmin:
    restart: on-failure
    image: dpage/pgadmin4:latest
    container_name: ligeiaai-pgadmin-1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS:-change-me}
    ports:
      - "5050:80"
    networks:
      - app_net
    logging: *default-logging
  redis:
    restart: on-failure
    image: redis:latest
    container_name: ligeiaai-redis-1
    volumes:
      - redis-data:/data
    expose:
      - 6379
    networks:
      - app_net
    logging: *default-logging
  redis-ts:
    restart: on-failure
    image: redislabs/redistimeseries:latest
    container_name: ligeiaai-redis-ts
    hostname: ligeiaai-redis-ts
    ports:
      - "${REDIS_TS_PORT:-6380}:6379"
    networks:
      - app_net
    logging: *default-logging
  mongo-dev:
    restart: on-failure
    container_name: mongo-dev
    hostname: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_NAME:-admin}
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-admin}
    networks:
      - app_net
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./data:/data/db
    logging: *default-logging

  mongo-express:
    restart: on-failure
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo-dev
    networks:
      - app_net
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_SERVER:-mongo-dev}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER_NAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS:-admin}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER_NAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_USER_PASS:-change-me}
    ports:
      - "${MONGO_ADMIN_PORT:-8081}:8081"
    volumes:
      - ./data:/data/db
    logging: *default-logging
networks:
  app_net:
    external: true
volumes:
  postgres-data1: null
  pgadmin-data: null
  redis-data: null
  couch-data: null
  mongodb-data: null
  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:ligeiaai-redis-ts:6379
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - app_net
