# Generated by Django 4.1.8 on 2023-04-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_roles_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='LAST_UPDT_DATE',
            field=models.DateField(null=True),
        ),
    ]
