# Generated by Django 4.1.11 on 2023-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_roles_last_updt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='roles',
            name='LAST_UPDT_DATEs',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
