# Generated by Django 4.1.11 on 2023-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_remove_roles_last_updt_date_roles_last_updt_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='LAST_UPDT_DATEs',
            new_name='LAST_UPDT_DATE',
        ),
    ]
