# Generated by Django 4.1.8 on 2023-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
        ('users', '0003_user_layer_name_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='layer_name',
            field=models.ManyToManyField(blank=True, related_name='layerName', to='layer.layer'),
        ),
    ]
