# Generated by Django 4.1.8 on 2023-05-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
        ('users', '0004_alter_user_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_layer', to='layer.layer'),
        ),
    ]
