# Generated by Django 4.1.8 on 2023-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_active_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address01',
            field=models.CharField(max_length=500, null=True, verbose_name='Address 01'),
        ),
        migrations.AddField(
            model_name='user',
            name='address02',
            field=models.CharField(max_length=500, null=True, verbose_name='Address 02'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Month'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Day'),
        ),
    ]
