# Generated by Django 4.1.8 on 2023-06-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_address01_user_address02_user_birth_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address01',
            new_name='address_01',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address02',
            new_name='address_02',
        ),
    ]
