# Generated by Django 4.1.8 on 2023-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_address01_user_address_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=1000, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=500, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(max_length=500, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(max_length=1000, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Birth Day'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(max_length=500, null=True, verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='State'),
        ),
    ]
