# Generated by Django 4.1.8 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_designation_user_instagram_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=1000, null=True, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=500, null=True, verbose_name='Ingstagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.CharField(max_length=500, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(max_length=500, null=True, verbose_name='Twitter'),
        ),
    ]
