# Generated by Django 4.1.8 on 2023-06-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_key_alter_user_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instagram',
            new_name='facebook',
        ),
    ]
