# Generated by Django 4.1.11 on 2023-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_instagram_user_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined_date',
            field=models.BigIntegerField(default=4100803080000, verbose_name='date joined tempt'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_updated_date',
            field=models.BigIntegerField(default=4100803080000, verbose_name='date updated tempt'),
        ),
    ]
