# Generated by Django 4.1.11 on 2023-11-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_date_joined_user_date_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_updated',
        ),
    ]
