# Generated by Django 4.1.11 on 2023-11-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_updated_date',
            new_name='date_updated',
        ),
    ]
