# Generated by Django 4.1.11 on 2023-11-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_date_joined_date_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.BigIntegerField(default=4100803080000, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.BigIntegerField(default=4100803080000, verbose_name='date updated'),
        ),
    ]
