# Generated by Django 4.1.11 on 2023-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_create_source_alter_item_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='END_DATETIME_tempt',
            field=models.BigIntegerField(default=9999999999999),
        ),
        migrations.AddField(
            model_name='item',
            name='START_DATETIME_tempt',
            field=models.BigIntegerField(default=1698182986000),
        ),
    ]
