# Generated by Django 4.1.11 on 2023-10-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_end_datetime_tempt_item_start_datetime_tempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='END_DATETIME',
        ),
        migrations.RemoveField(
            model_name='item',
            name='START_DATETIME',
        ),
    ]
