# Generated by Django 4.1.11 on 2023-10-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_end_datetime_remove_item_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='END_DATETIME_tempt',
            new_name='END_DATETIME',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='START_DATETIME_tempt',
            new_name='START_DATETIME',
        ),
    ]
