# Generated by Django 4.1.11 on 2023-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='timestampt',
            field=models.BigIntegerField(null=True),
        ),
    ]
