# Generated by Django 4.1.11 on 2023-10-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_time_event_timestampt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interval',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
