# Generated by Django 4.1.11 on 2023-10-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_interval_event_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='timestampt',
            new_name='time',
        ),
    ]
