# Generated by Django 4.1.8 on 2023-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='DB_SETTINGS',
            field=models.JSONField(null=True),
        ),
    ]
