# Generated by Django 4.1.8 on 2023-05-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_layer_db_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='DATA_SOURCE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='LAST_UPDT_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='ROW_ID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='layer',
            name='VERSION',
            field=models.CharField(max_length=32),
        ),
    ]
