# Generated by Django 4.1.8 on 2023-05-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0003_layer_data_source_alter_layer_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='LAYER_ORDER',
        ),
    ]
