# Generated by Django 4.1.11 on 2023-11-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0004_remove_layer_layer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='layer',
            name='LAST_UPDT_DATES',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
