# Generated by Django 4.1.11 on 2023-11-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0005_remove_layer_last_updt_date_layer_last_updt_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='LAST_UPDT_DATES',
            new_name='LAST_UPDT_DATE',
        ),
    ]
