# Generated by Django 4.1.8 on 2023-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('PHONE_NUMBER', models.CharField(max_length=100)),
                ('MESSAGE', models.CharField(max_length=5000)),
                ('ROW_ID', models.CharField(max_length=32)),
            ],
        ),
    ]
