# Generated by Django 4.1.8 on 2023-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-11', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='7b083c8e88464494ab99cfa9fa1555e1', max_length=32),
        ),
    ]
