# Generated by Django 4.1.8 on 2023-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0002_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='d0cf5b50cfbc4939885bafd67c9bcba6', max_length=32),
        ),
    ]
