# Generated by Django 4.1.8 on 2023-05-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0003_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='3b26ef027f034bd99888dbb1ccb51a2c', max_length=32),
        ),
    ]
