# Generated by Django 4.1.8 on 2023-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0005_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-31', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='c634a3f6342b48a7810acaba216b24e9', max_length=32),
        ),
    ]
