# Generated by Django 4.1.8 on 2023-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0009_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='ef5abee573d845999e449ebd193f2550', max_length=32),
        ),
    ]
