# Generated by Django 4.1.8 on 2023-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0010_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='248c6e3515f74e19bc96ffa17b309ade', max_length=32),
        ),
    ]
