# Generated by Django 4.1.8 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0011_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='8f79eab2af7e4577931366f503402586', max_length=32),
        ),
    ]
