# Generated by Django 4.1.8 on 2023-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0012_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='a98780d759104f6b86dc806f706a9b89', max_length=32),
        ),
    ]
