# Generated by Django 4.1.8 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0014_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='1ab3fc918bdd4fcebcb59d22169f2a43', max_length=32),
        ),
    ]
