# Generated by Django 4.1.8 on 2023-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0015_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='cf50080a5c7f4c1a9a972375b0036097', max_length=32),
        ),
    ]
