# Generated by Django 4.1.8 on 2023-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0016_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='c5b066abe43f4f6493418b96c69d196e', max_length=32),
        ),
    ]
