# Generated by Django 4.1.8 on 2023-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0017_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='6949c846f6504eaaa7d3029996170ad5', max_length=32),
        ),
    ]
