# Generated by Django 4.1.8 on 2023-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0020_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='4dbb481fa5ff4ab7a3c88ed526b819da', max_length=32),
        ),
    ]
