# Generated by Django 4.1.8 on 2023-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0023_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='9a0bbf3ca21448ad905f64438b2628b3', max_length=32),
        ),
    ]
