# Generated by Django 4.1.8 on 2023-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0025_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-07-03', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='3dc0e7ddead143eebe17e4325124b827', max_length=32),
        ),
    ]
