# Generated by Django 4.1.11 on 2023-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0026_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-10-09', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='NAME',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='32ac5915c12243eba9c2ffcff104dbc3', max_length=32),
        ),
    ]
