# Generated by Django 4.1.11 on 2023-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0027_alter_uom_last_updt_date_alter_uom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='CODE',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-10-16', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='5dc81dde7624438eb4b5d37ea04776ef', max_length=32),
        ),
    ]
