# Generated by Django 4.1.11 on 2023-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0028_uom_code_alter_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='LAST_UPDT_DATE_date',
            field=models.BigIntegerField(default=1699018031000, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-11-03', null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='60d54b66fd0c410eab8811f6e34448b5', max_length=32),
        ),
    ]
