# Generated by Django 4.1.11 on 2023-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0029_uom_last_updt_date_date_alter_uom_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uom',
            name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='29fd268d40ec4f0a8fe868eb13d53fcf', max_length=32),
        ),
    ]
