# Generated by Django 4.1.11 on 2023-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0030_remove_uom_last_updt_date_alter_uom_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uom',
            old_name='LAST_UPDT_DATE_date',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='ff7140b599f34024a7bdd3e8b0eba93f', max_length=32),
        ),
    ]
