# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom', '0031_rename_last_updt_date_date_uom_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='VERSION',
            field=models.CharField(default='7d55d49b252440c49bcb026c20fd50d1', max_length=32),
        ),
    ]
