#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export PG_DB="${PG_DB:-ligeia}"
export PG_USER="${PG_USER:-postgres}"
export PG_PASS="${PG_PASS:-postgres}"
export PG_HOST="${PG_HOST:-postgres}"
export PG_PORT="${PG_PORT:-5432}"

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${PG_DB}",
        user="${PG_USER}",
        password="${PG_PASS}",
        host="${PG_HOST}",
        port="${PG_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Waiting for PostgreSQL to become available....:-("
 sleep 1
done
>&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"
