#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd backend

# python manage.py makemigrations --no-input
# python manage.py migrate --no-input
python manage.py collectstatic --no-input

RUN_MODE="${DJANGO_RUN_MODE:-asgi}"

if [[ "$RUN_MODE" == "dev" ]]; then
  exec python manage.py runserver 0.0.0.0:8000
elif [[ "$RUN_MODE" == "wsgi" ]]; then
  exec gunicorn core.wsgi:application \
    --bind 0.0.0.0:8000 \
    --workers "${GUNICORN_WORKERS:-3}" \
    --timeout "${GUNICORN_TIMEOUT:-120}"
else
  exec daphne -b 0.0.0.0 -p 8000 core.asgi:application
fi
