# Generated by Django 4.1.8 on 2023-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0003_alter_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-05-11', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='481f4ac086614e0ba1fb1ab653cbb697', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='3d3ca22f33524b3fbad661db5667e09e', max_length=32),
        ),
    ]
