# Generated by Django 4.1.8 on 2023-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0004_alter_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4bc62737b1c14261ab467fe349b9ea67', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='e6e6c4cced7f433bb87188f111fa6205', max_length=32),
        ),
    ]
