# Generated by Django 4.1.8 on 2023-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0009_alter_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-06-17', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d5cf91bb36c24821b89b7105964e3bbd', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='d1c2bf5c42b9486e9dfadd015bf7972d', max_length=32),
        ),
    ]
