# Generated by Django 4.1.8 on 2023-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0010_alter_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-06-22', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='5a8412b7b5b54a188511a74161871a87', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='cf2b72fecbc7408fb05cf22101f91289', max_length=32),
        ),
    ]
