# Generated by Django 4.1.8 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0013_alter_uom_base_unit_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='be1b8b0ce56349b9bc43c7f8f2b4f0f6', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='cbd78c25e962414dad306bdf45956483', max_length=32),
        ),
    ]
