# Generated by Django 4.1.8 on 2023-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0015_alter_uom_base_unit_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-06-24', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='3d0eb678e3af4b2c91513f04b1daa92b', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='4a435b8a897d4be6ab3c99aa341f6f3e', max_length=32),
        ),
    ]
