# Generated by Django 4.1.8 on 2023-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0017_alter_uom_base_unit_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='78bd8aa659a74e1ba608b6cf0b079c46', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='5bd7e27af44d49e98310233bc9916d70', max_length=32),
        ),
    ]
