# Generated by Django 4.1.8 on 2023-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0018_alter_uom_base_unit_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='5a25753e797647a69082101dd63ecbc7', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='9162867c47074f37b20549db2b90c5e6', max_length=32),
        ),
    ]
