# Generated by Django 4.1.8 on 2023-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0020_alter_uom_base_unit_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0a0a163968e04be0b86ba689298ccd97', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='cca03abe0e344d5997840345aeea10aa', max_length=32),
        ),
    ]
