# Generated by Django 4.1.11 on 2023-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0029_alter_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom_base_unit',
            name='CODE',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-10-16', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='395b11db89b046ca975f69e1c1c5bfba', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='ba0f87053cec499faffaf83a39cd582d', max_length=32),
        ),
    ]
