# Generated by Django 4.1.11 on 2023-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0030_uom_base_unit_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE_date',
            field=models.BigIntegerField(default=1699018031000, null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
            field=models.DateField(default='2023-11-03', null=True),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='65e572094fa7493a8e24b0ba28c5be22', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='38f98da6ae50467a8d9710e1e53ef08c', max_length=32),
        ),
    ]
