# Generated by Django 4.1.11 on 2023-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0031_uom_base_unit_last_updt_date_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uom_base_unit',
            name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='9925657d53a6464cb94531adda0adc04', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='ae11b74113b949079e1bcf50ab3791bf', max_length=32),
        ),
    ]
