# Generated by Django 4.1.11 on 2023-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0032_remove_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uom_base_unit',
            old_name='LAST_UPDT_DATE_date',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='062afc88920c4d278b6f98445bc225c8', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='ab5c9578b271402aafe61de95ee64b18', max_length=32),
        ),
    ]
