# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uom_base_unit', '0033_rename_last_updt_date_date_uom_base_unit_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom_base_unit',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c768645ccbe5419990830bdb69228048', max_length=32),
        ),
        migrations.AlterField(
            model_name='uom_base_unit',
            name='VERSION',
            field=models.CharField(default='d430149e66ed4d568f740a3e01d4b064', max_length=32),
        ),
    ]
