# Generated by Django 4.1.11 on 2023-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0012_alter_type_last_updt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='type',
            name='LAST_UPDT_DATES',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
