# Generated by Django 4.1.11 on 2023-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0013_remove_type_last_updt_date_type_last_updt_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='LAST_UPDT_DATES',
            new_name='LAST_UPDT_DATE',
        ),
    ]
