# Generated by Django 4.1.11 on 2023-09-27 14:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_ref',
            fields=[
                ('TYPE', models.CharField(max_length=100)),
                ('PROPERTY_NAME', models.CharField(max_length=50)),
                ('VALID_TYPE', models.CharField(max_length=250)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('DESCRIPTION_ID', models.CharField(max_length=250, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('ROW_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.DateField(default=django.utils.timezone.now, null=True)),
                ('VERSION', models.CharField(default=uuid.uuid4, max_length=32)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
