# Generated by Django 4.1.8 on 2023-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_dashboard',
            name='START_DATETIME',
            field=models.DateField(db_index=True, default='2023-01-01', null=True),
        ),
    ]
