# Generated by Django 4.1.11 on 2023-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_dashbord', '0002_bi_dashboard_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_dashboard',
            name='DASHBOARD_USER',
            field=models.JSONField(null=True),
        ),
    ]
