# Generated by Django 4.1.8 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_type', '0002_rename_roles_type_roles_type_roles_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_type',
            name='PARENT',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
