# Generated by Django 4.1.11 on 2023-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('ITEM_ID', models.CharField(db_index=True, max_length=32, null=True)),
                ('EVENT_TYPE', models.CharField(max_length=14)),
                ('TAG_ID', models.CharField(default='6bb70ceb62bd4111bd0c05b8a3687714', max_length=32, primary_key=True, serialize=False)),
                ('START_DATETIME', models.BigIntegerField()),
                ('PARENT_TAG_ID', models.CharField(max_length=32, null=True)),
                ('NAME', models.CharField(db_index=True, max_length=110, null=True)),
                ('DESCRIPTION', models.CharField(max_length=1000, null=True)),
                ('UOM', models.CharField(max_length=100, null=True)),
                ('UOM_QUANTITY_TYPE', models.CharField(max_length=100, null=True)),
                ('UOM_NAME', models.CharField(max_length=100, null=True)),
                ('SHORT_NAME', models.CharField(max_length=100, null=True)),
                ('DATA_TYPE', models.CharField(max_length=100, null=True)),
                ('DERIVE_EQUATION', models.CharField(max_length=1000, null=True)),
                ('EXCEPTION_DEV', models.CharField(max_length=1000, null=True)),
                ('EXCEPTION_DEV_TYPE', models.CharField(max_length=1000, null=True)),
                ('NODE_NAME', models.CharField(max_length=100, null=True)),
                ('PROCESS_NAME', models.CharField(max_length=100, null=True)),
                ('SOURCE_NAME', models.CharField(max_length=100, null=True)),
                ('STEPPED', models.CharField(max_length=100, null=True)),
                ('DATA_ACCESS_TYPE', models.CharField(max_length=200, null=True)),
                ('LAYER_NAME', models.CharField(max_length=50)),
                ('NODE_DUMP', models.CharField(max_length=2000, null=True)),
                ('NORMAL_MAXIMUM', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('NORMAL_MINIMUM', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('LIMIT_LOLO', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('LIMIT_HIHI', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('EVENT_NOTIFIER', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('NODE_CLASS', models.CharField(max_length=20, null=True)),
                ('HISTORIZING', models.CharField(max_length=10, null=True)),
                ('MINIMUM_SAMPLING_INTERVAL', models.DecimalField(decimal_places=12, max_digits=28, null=True)),
                ('PERIOD', models.CharField(max_length=20, null=True)),
                ('END_DATETIME', models.BigIntegerField(default='9000-01-01')),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.BigIntegerField()),
                ('VERSION', models.CharField(max_length=32, null=True)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(db_index=True, max_length=32, null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
                ('TRANSACTION_TYPE', models.CharField(max_length=2000, null=True)),
                ('TRANSACTION_PROPERTY', models.CharField(max_length=2000, null=True)),
                ('UPDATE_SOURCE', models.CharField(default='x', max_length=100, null=True)),
                ('CREATE_SOURCE', models.CharField(default='x', max_length=100, null=True)),
            ],
        ),
    ]
