# Generated by Django 4.1.11 on 2023-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='LAST_UPDT_USER',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='49431793236c4607b51c72814d0af38f', max_length=32, primary_key=True, serialize=False),
        ),
    ]
