# Generated by Django 4.1.11 on 2023-10-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tags_last_updt_user_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='LAST_UPDT_USER',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='7dc60e310e964ec791e9064e17c3ba12', max_length=32, primary_key=True, serialize=False),
        ),
    ]
