# Generated by Django 4.1.11 on 2023-10-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tags_last_updt_user_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='LAST_UPDT_USER',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='5f707f78d6524c7888c1303f6067c2ef', max_length=32, primary_key=True, serialize=False),
        ),
    ]
