# Generated by Django 4.1.11 on 2023-10-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tags_last_updt_user_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='END_DATETIME',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='EVENT_TYPE',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='698e84519c1c4d15b084f62f1b4c8caa', max_length=32, primary_key=True, serialize=False),
        ),
    ]
