# Generated by Django 4.1.11 on 2023-10-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tags_end_datetime_alter_tags_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='UOM',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='UOM_NAME',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='UOM_QUANTITY_TYPE',
        ),
        migrations.AddField(
            model_name='tags',
            name='UOM_CODE',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='f88944072f3a47199020515a6b137368', max_length=32, primary_key=True, serialize=False),
        ),
    ]
