# Generated by Django 4.1.11 on 2023-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_remove_tags_uom_remove_tags_uom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='0ecfc341067046a5ac65f79ca12995bb', max_length=32, primary_key=True, serialize=False),
        ),
    ]
