# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_tags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='END_DATETIME',
            field=models.BigIntegerField(default=9999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TAG_ID',
            field=models.CharField(default='b184529d055a4f038e60861ee8d5f8a1', max_length=32, primary_key=True, serialize=False),
        ),
    ]
