# Generated by Django 4.1.8 on 2023-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0007_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='4e1cdf617fd6415588c70ea52d86c00f', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='d38a83aec0af4449b5a97a22cc6b95b6', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='395c83465bd349edaefc3c5c44768096', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='4c3bf31e9126466784408125752cc894', max_length=32, null=True),
        ),
    ]
