# Generated by Django 4.1.8 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0010_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='45511883755d475b9b64574f67967a07', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='283afc29b3854ad3b726959bd4486d0d', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='7ef43cc5ef5f4670852b4e1161ce6037', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='2c8161fc5b634f728492de2c6b2e5f2d', max_length=32, null=True),
        ),
    ]
