# Generated by Django 4.1.8 on 2023-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0011_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='0131fe50cec44be4811d86d577050eaf', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='f24dc70023084859b76ab422e415fbb3', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='29042a902e0e408cbde6412005259e65', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='fb9a7740591a449aaa9537528c7b7073', max_length=32, null=True),
        ),
    ]
