# Generated by Django 4.1.8 on 2023-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0022_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='560453500d4e485c85b524aa7bd8aa24', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7dc147e9a240486d86885e0a292f6af1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='3d743f95e846472c86d301bf20c97dd3', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='5dfcad3e0f0d4b82a09345a218541e2c', max_length=32, null=True),
        ),
    ]
