# Generated by Django 4.1.8 on 2023-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0025_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_calculated',
            name='OPERATIONS_TYPE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='feb007d21bec446aaa929c8f5beec525', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='LAST_UPDATE_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='be790fc9f1b9468e8ae07cc7e4c96a76', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='87604f20acf140d78f1070e38c23d4d2', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='bded45fa07274bfa8eb95c6b6ada24a8', max_length=32, null=True),
        ),
    ]
