# Generated by Django 4.1.8 on 2023-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0026_tags_calculated_operations_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='b2df9b5a5f3b4e7f9c75819072381425', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='4ef9d8b69a9946b184c519923e9c1fc4', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='abbd0524ac22407d95f4c6829776504b', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='719673c007494a069cfedaf39376ef09', max_length=32, null=True),
        ),
    ]
