# Generated by Django 4.1.8 on 2023-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0027_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_calculated',
            name='SHORT_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='5c63408a386544dc8d3b8e28c2c50bfb', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='305d6b0731b14003a8fce90f677acec1', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='22b4a30211414b2988620a78f9afd49d', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='7cbe819bd1724122b8287d532b3140b0', max_length=32, null=True),
        ),
    ]
