# Generated by Django 4.1.8 on 2023-08-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0028_tags_calculated_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='83e17e0798cc4f749114268670f5ef74', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6cd7c0889f914605ab9b74da853c867a', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='42128c5ec59b4d36b5017c52fd65c924', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='08f1abcef250473eab2230ed0cdefb4a', max_length=32, null=True),
        ),
    ]
