# Generated by Django 4.1.8 on 2023-09-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0030_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_calculated',
            name='RPM',
            field=models.DecimalField(decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='1c7cf21723494710b20100d697d8d12c', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e2e06db520194325a002c65e4219b766', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='31d696e51f11436d9da4e8e33d24755d', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='8f3f39a0b335456d84ff3f8f934ab2ae', max_length=32, null=True),
        ),
    ]
