# Generated by Django 4.1.11 on 2023-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0031_tags_calculated_rpm_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_calculated',
            name='RPM',
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='02bd6af58a314ce2920916f3f0d72607', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='634831ea69534f3b89cc863396d03d3d', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='7216e4f82348401bbb42dbaedee437e6', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='eec1cfc72935481fa3b0b5397120c4a5', max_length=32, null=True),
        ),
    ]
