# Generated by Django 4.1.11 on 2023-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0032_remove_tags_calculated_rpm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags_calculated',
            old_name='LAST_UPDATE_DATE',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.RenameField(
            model_name='tags_calculated',
            old_name='LAST_UPDATE_USER',
            new_name='LAST_UPDT_USER',
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='bbcb268697af4c4d82b31c45498c6f61', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='86452619e683492c90a78b70e60b5ffc', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='f64d77f1971e44229d64a6bbaab8cc72', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='48c89c9592814e219a4d9dc4b19c2b00', max_length=32, null=True),
        ),
    ]
