# Generated by Django 4.1.11 on 2023-10-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0033_rename_last_update_date_tags_calculated_last_updt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='205def06be4a491c8d1f250fa9cfd185', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0110b5e048764d7cb1cba713a5827652', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='741d8079d4144949b3a118ed322321ae', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='8d5f4adc0c8445daacb0716b183482d2', max_length=32, null=True),
        ),
    ]
