# Generated by Django 4.1.11 on 2023-10-17 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0034_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='END_DATETIME',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='3bfb7b53d90643e9b482065400a52937', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='f44c3d0522a64c9a8b4d750491e7a10a', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='START_DATETIME',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='91737d568d5241c294f1481196fa3f65', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='8d5708bcc53d4257bf0c479ae13641a0', max_length=32, null=True),
        ),
    ]
