# Generated by Django 4.1.11 on 2023-10-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0035_alter_tags_calculated_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_calculated',
            name='END_DATETIME_big_int',
            field=models.BigIntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='tags_calculated',
            name='LAST_UPDT_DATE_big_int',
            field=models.BigIntegerField(default=1672520400),
        ),
        migrations.AddField(
            model_name='tags_calculated',
            name='START_DATETIME_bigint',
            field=models.BigIntegerField(default=1672520400),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='d2bfc1a96337409b8d75829f86ac3d4b', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='b7df7473e3574e35a740fa0185561cdf', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='106c66dadc4f404caffeb265db0e1862', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='51d3fcd5919d49a5b2deaf3baa763821', max_length=32, null=True),
        ),
    ]
