# Generated by Django 4.1.11 on 2023-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0036_tags_calculated_end_datetime_big_int_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_calculated',
            name='END_DATETIME',
        ),
        migrations.RemoveField(
            model_name='tags_calculated',
            name='LAST_UPDT_DATE',
        ),
        migrations.RemoveField(
            model_name='tags_calculated',
            name='START_DATETIME',
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='7f2bed3e90794f4f92879c4fabb90b57', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='5e71726812cb480c86001b1335025fb0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='e25dfbff359c42b78006ae79388f8a1b', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='92aa88d0e6934889b036b922cfed5bc4', max_length=32, null=True),
        ),
    ]
