# Generated by Django 4.1.11 on 2023-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0037_remove_tags_calculated_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags_calculated',
            old_name='END_DATETIME_big_int',
            new_name='END_DATETIME',
        ),
        migrations.RenameField(
            model_name='tags_calculated',
            old_name='LAST_UPDT_DATE_big_int',
            new_name='LAST_UPDT_DATE',
        ),
        migrations.RenameField(
            model_name='tags_calculated',
            old_name='START_DATETIME_bigint',
            new_name='START_DATETIME',
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='ed5d88e1f779411dbf913eae297bcdb9', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='a3bd6fe99b8145d48819ea28a47eaa02', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='be6b0338fc9f44998c87236a5868f822', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='85cad45890ea4cd0b8215c87f295264f', max_length=32, null=True),
        ),
    ]
