# Generated by Django 4.1.11 on 2023-10-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0038_rename_end_datetime_big_int_tags_calculated_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='74b8bc8a5a1947aab010e83ade747471', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='81fa2a8545874dfea753ac1df19bbbcd', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='7bca332f21f546f7a797db10b2630313', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='e0d0fbeab14b4fc29b1000807737d3f1', max_length=32, null=True),
        ),
    ]
