# Generated by Django 4.1.11 on 2023-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0039_alter_tags_calculated_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_calculated',
            name='UOM_CODE',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='d727cae807204f638f039dec86cd6fee', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='e209f0fdd8f54acd83dba7f592043d50', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='bf27856620e541f9a78da6b9215e9548', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='f6356025196443d4b21b9977bcef2df7', max_length=32, null=True),
        ),
    ]
