# Generated by Django 4.1.11 on 2023-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0040_tags_calculated_uom_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_calculated',
            name='UOM',
        ),
        migrations.RemoveField(
            model_name='tags_calculated',
            name='UOM_NAME',
        ),
        migrations.RemoveField(
            model_name='tags_calculated',
            name='UOM_QUANTITY_TYPE',
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='2e0ea641ab9f4c63bf61a04270a384af', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c864c585fee5447bb6f9e964f75a45bf', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='0c186aee855942f68594a17e9f1cf1d3', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='11343aeb5c804d15842d9b0cf754a1df', max_length=32, null=True),
        ),
    ]
