# Generated by Django 4.1.11 on 2023-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0041_remove_tags_calculated_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_calculated',
            name='END_DATETIME',
            field=models.BigIntegerField(default=9999999999000),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ITEM_ID',
            field=models.CharField(db_index=True, default='cf9de075d348431b9ecc90f3ec1d7ccb', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='LAST_UPDT_DATE',
            field=models.BigIntegerField(default=1672520400000),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='7701fb8f9e394a1bb2133783a888bb86', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='TAG_ID',
            field=models.CharField(default='999db84af5ae4e5584a6b3f1bd661ae2', max_length=32),
        ),
        migrations.AlterField(
            model_name='tags_calculated',
            name='VERSION',
            field=models.CharField(default='036177a00c894723bca1d47b921cb879', max_length=32, null=True),
        ),
    ]
