from .consumers_.alarms import AlarmsConsumer
from .consumers_.live_data import WSLiveConsumer
from .consumers_.live_last_data import WSConsumeOnlyLastData
from .consumers_.backfill import WSConsumerBackfill
from .consumers_.importTag import ImportTagConsumer
from .consumers_.tabular import WSLiveTabularConsumer
from .consumers_.test import TestConsumer
from .consumers_.inkai_alarms import WSInkaiAlarmsConsumer
from .consumers_.inkai_notifications import WSInkaiNotificationsConsumer
from .consumers_.inkai_unread_notifications import WSInkaiUnreadNotificationsConsumer
from .consumers_.inkai_warnings import WSInkaiWarningsConsumer
from .consumers_.inkai_logs import WSInkaiLogsConsumer
from .consumers_.inkai_all_notifications import WSInkaiAllNotificationsConsumer
from .consumers_.inkai_connect_status import WSInkaiLastWarningsConsumer
from .consumers_.inkai_widget_alarms import WSInkaiWidgetAlarmsConsumer
from .consumers_.inkai_communications_status import WSInkaiCommunicationsConsumer
from .consumers_.tags_status import WSConsumeTagsStatus

# from .consumers_.inkai_anomaly import WSAnomalyLiveConsumer
