# Generated by Django 4.1.11 on 2023-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_event',
            name='pdf_file',
            field=models.BinaryField(null=True),
        ),
    ]
