# Generated by Django 4.1.11 on 2023-10-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0002_item_event_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_event',
            old_name='pdf_file',
            new_name='PDF_FILE',
        ),
    ]
