# Generated by Django 4.1.11 on 2023-10-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0003_rename_pdf_file_item_event_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_event',
            name='CHAR16',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item_event',
            name='CHAR17',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item_event',
            name='CHAR18',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
