# Generated by Django 4.1.11 on 2023-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0004_item_event_char16_item_event_char17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_event',
            name='CHAR19',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item_event',
            name='CHAR20',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
