# Generated by Django 4.1.11 on 2023-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0005_item_event_char19_item_event_char20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_event',
            name='CHAR10',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR2',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
