# Generated by Django 4.1.11 on 2023-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0006_alter_item_event_char10_alter_item_event_char2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_event',
            name='CHAR1',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR11',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR12',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR13',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR14',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR15',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR16',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR17',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR18',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR19',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR20',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR3',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR4',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR5',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR6',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR7',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR8',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item_event',
            name='CHAR9',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
