# Generated by Django 4.1.11 on 2023-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_event', '0007_alter_item_event_char1_alter_item_event_char11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_event',
            name='PDF_FILE_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
