# Generated by Django 4.1.8 on 2023-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0005_remove_roles_property_roles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_property',
            name='LAST_UPDT_DATE',
            field=models.DateField(null=True),
        ),
    ]
