# Generated by Django 4.1.8 on 2023-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0006_roles_property_last_updt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_property',
            name='PARENT',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
