# Generated by Django 4.1.13 on 2023-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0007_roles_property_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles_property',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='roles_property',
            name='LAST_UPDT_DATEs',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
