# Generated by Django 4.1.13 on 2023-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_property', '0008_remove_roles_property_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles_property',
            old_name='LAST_UPDT_DATEs',
            new_name='LAST_UPDT_DATE',
        ),
    ]
