# Generated by Django 4.1.11 on 2023-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_property', '0003_alter_type_property_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_property',
            name='READ_ONLY',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
