# Generated by Django 4.1.11 on 2023-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_property', '0004_type_property_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_property',
            name='LAST_UPDT_DATE',
        ),
        migrations.AddField(
            model_name='type_property',
            name='LAST_UPDT_DATEs',
            field=models.BigIntegerField(default=1699356132000),
        ),
    ]
