# Generated by Django 4.1.11 on 2023-11-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_property', '0005_remove_type_property_last_updt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_property',
            old_name='LAST_UPDT_DATEs',
            new_name='LAST_UPDT_DATE',
        ),
    ]
