# Generated by Django 4.1.11 on 2023-10-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_system',
            fields=[
                ('TABLE_NAME', models.CharField(max_length=100)),
                ('PROP_ID', models.CharField(max_length=100)),
                ('FILE', models.BinaryField()),
                ('FILE_NAME', models.CharField(max_length=100)),
                ('HIDDEN', models.CharField(max_length=5, null=True)),
                ('LAST_UPDT_USER', models.CharField(max_length=100, null=True)),
                ('LAST_UPDT_DATE', models.BigIntegerField(default=1697757191000, null=True)),
                ('VERSION', models.CharField(max_length=32, null=True)),
                ('DB_ID', models.CharField(max_length=32, null=True)),
                ('ROW_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('REV_GRP_ID', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
