# Generated by Django 4.1.8 on 2023-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0003_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='c3969e6266f74a8cb8e528a99553a0da', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='6171541882c544d584ac6bcd52215d39', max_length=32),
        ),
    ]
