# Generated by Django 4.1.8 on 2023-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0005_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources_drawer',
            name='LAYER_LEVEL',
            field=models.DecimalField(decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='06998502a78a43239b3f01a6a0a1264a', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='c4df0d6398f444a386f60cc1c8e1a937', max_length=32),
        ),
    ]
