# Generated by Django 4.1.8 on 2023-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0006_resources_drawer_layer_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='6da3003679e543f0a84a89c0dc684933', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='c12615c9cc064b579b74dc880aa07018', max_length=32),
        ),
    ]
