# Generated by Django 4.1.8 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0007_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='fa90dfa5ebf040e28e7144ffd92fd15d', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='05d31b81e3374100aff10e2e185bd409', max_length=32),
        ),
    ]
