# Generated by Django 4.1.8 on 2023-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0008_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='235369493eb94fa7a54bf1e9fe538147', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='b03051078c014ed6aaead244172b7947', max_length=32),
        ),
    ]
