# Generated by Django 4.1.8 on 2023-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0013_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='169b71c11be044f0b4e8135cfec58739', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='4483cf1df0c14b2cb6bb79183130d517', max_length=32),
        ),
    ]
