# Generated by Django 4.1.8 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0015_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='5a79a65df3fc431e802358c74baa25de', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='a859c2d9e34c44a2b36340b26cbb841c', max_length=32),
        ),
    ]
