# Generated by Django 4.1.8 on 2023-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0021_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0973b9d3979e4ab09c32ff34677aa1ed', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='07eb0d108ca64b9994511ac7b56b3088', max_length=32),
        ),
    ]
