# Generated by Django 4.1.8 on 2023-06-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0025_alter_resources_drawer_row_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='HIDDEN',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='18effe4e153e48009a3e626b0fe3d440', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='fb683481122d4737a69a9cd9cac6ef37', max_length=32),
        ),
    ]
