# Generated by Django 4.1.8 on 2023-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_drawer', '0026_alter_resources_drawer_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_drawer',
            name='ROW_ID',
            field=models.CharField(db_index=True, default='0ca3ca545e7d45c5aada8037f6ad03a2', max_length=32),
        ),
        migrations.AlterField(
            model_name='resources_drawer',
            name='VERSION',
            field=models.CharField(default='2703bf764af742248a91ac15e5f63488', max_length=32),
        ),
    ]
