# Generated by Django 4.1.8 on 2023-06-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification', models.BooleanField(default=False)),
                ('font_size', models.DecimalField(decimal_places=12, default=14, max_digits=28)),
                ('font_weight', models.DecimalField(decimal_places=12, default=400, max_digits=28)),
                ('overview_orientation', models.CharField(default='horizontal', max_length=500)),
                ('thema', models.CharField(max_length=500)),
                ('language', models.CharField(default='light', max_length=500)),
                ('full_screen', models.CharField(default='False', max_length=500)),
                ('ROW_ID', models.CharField(max_length=100, null=True)),
                ('USER', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
