# Generated by Django 4.1.8 on 2023-06-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='state_settings',
            field=models.JSONField(null=True),
        ),
    ]
