# Generated by Django 4.1.8 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_user_settings_state_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_settings',
            old_name='state_settings',
            new_name='drawer_settings',
        ),
        migrations.AddField(
            model_name='user_settings',
            name='item_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user_settings',
            name='others_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user_settings',
            name='overview_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='language',
            field=models.CharField(default='English (US)', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='thema',
            field=models.CharField(default='light', max_length=500),
        ),
    ]
