# Generated by Django 4.1.8 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_rename_state_settings_user_settings_drawer_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='full_screen',
            field=models.BooleanField(default=False),
        ),
    ]
