# Generated by Django 4.1.8 on 2023-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0004_alter_user_settings_full_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='alarm_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='overview_orientation',
            field=models.CharField(default='vertical', max_length=500),
        ),
    ]
