# Generated by Django 4.1.11 on 2023-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_widget_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bi_widget_property',
            name='PROPERTY_TYPE',
            field=models.CharField(db_index=True, max_length=155, null=True),
        ),
    ]
