# Generated by Django 4.1.11 on 2023-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_tags_tag_id'),
        ('bi_widget_property', '0002_alter_bi_widget_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_widget_property',
            name='PROPERTY_TAG',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tags.tags'),
        ),
    ]
