# Generated by Django 4.1.11 on 2023-10-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_widget_property', '0003_bi_widget_property_property_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bi_widget_property',
            name='PROPERTY_TAG_CAL',
        ),
    ]
