# Generated by Django 4.1.11 on 2023-10-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_calculated', '0039_alter_tags_calculated_item_id_and_more'),
        ('bi_widget_property', '0004_remove_bi_widget_property_property_tag_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi_widget_property',
            name='PROPERTY_TAG_CAL',
            field=models.ManyToManyField(blank=True, related_name='tags_calculated', to='tags_calculated.tags_calculated'),
        ),
    ]
